version: "3"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:80"
    platform: linux/amd64
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 256M
        reservations:
          cpus: "0.1"
          memory: 128M
